List<String> sfucolumnNames = [
  'sfuNo',
  'fuc',
  'icc',
  'ictc',
  'occ',
  'octc',
  'ec',
  'cg',
  'dl',
  'vi',
  'Add',
  'Delete',
];
List<String> sfucolumnLabelNames = [
  'SFU No',
  'Fuse unit Condition',
  'Incoming Cable Condition',
  'Incoming Cable Termination Condition',
  'Outgoing Cable Condition',
  'Outgoing Cable Termination Condition',
  'Earthing Condition',
  'Cable Glands',
  'Door lock',
  'Voltage Indicator',
  'Add',
  'Delete',
];
List<String> chargercolumnNames = [
  'CN',
  'DC',
  'CGCA',
  'CGCB',
  'CGCCA',
  'CGCCB',
  'dl',
  'ARM',
  'EC',
  'CC',
];
List<String> chargercolumnLabelNames = [
  'Charger No',
  'Display Condition',
  'A',
  'B',
  'A',
  'B',
  'Door lock',
  'Availability of Rubber mat',
  'Earthing Condition',
  'Charger Cleaness',
];
